import '../styles/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-900 text-gray-100">
        {children}
      </body>
    </html>
  )
}
